apiVersion: v1
kind: Secret
metadata:
  name: baemtli-secrets
  namespace: baemtli-project
type: Opaque
stringData:
  mysql-root-password: "qJlqy+Vff3dDcABGPRXI62NdXD0nbGjPw3uSzXxhQm8="
  mysql-password: "piexu0VTFbFKRjfzof0OEr7lvuYjLOQ+ydFt8fUC/9s="
  jwt-secret: "TJNSPIcV2Isi6XG0jYoK1/aFyRmZ1rIqxhF48kBjnMc="