# Azure MSSQL cloud instance for dev

# API Versioning
server.servlet.context-path=/api/v1
# Application name
spring.application.name=baemtli

# Syntax von Variablen ohne Fallback: ${ENV_VARIABLE_NAME}
spring.datasource.url=jdbc:sqlserver://${DB_HOST}:1433;database=${DB_NAME};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate Dialekt für Microsoft SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl