# Azure MSSQL cloud instance for dev

# Spring Profile
spring.profiles.active=dev

# Application name
spring.application.name=baemtli

# API Versioning
server.servlet.context-path=/api/v1

# DATABASE CONNECTION
# Syntax von Variablen ohne Fallback: ${ENV_VARIABLE_NAME}
# spring.datasource.url=jdbc:sqlserver://${DB_HOST}:1433;database=${DB_NAME};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.url=jdbc:sqlserver://${DB_HOST}:1433;databaseName=${DB_NAME};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# Hibernate dialect for Microsoft SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate-dialect=org.hibernate.dialect.SQLServerDialect

# Erzwingt, dass Hibernate EXAKT die Namen aus den @Column-Annotationen nimmt (bug with non-matching table names Java Class <-> MSSQL Azure DB)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl