name: Build, push, deploy to Azure

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  # =================================================================
  # JOB 1: Detector: Did frontend or backend or both receive changes?
  # =================================================================
  changes:
    runs-on: ubuntu-latest
    # Define outputs for this action
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: Check for changes in folders
        id: filter
        uses: dorny/paths-filter@v3
        with:
          # Define rules
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/**'
            frontend:
              - 'frontend/**'
              - '.github/workflows/**'

  # =================================================================
  # JOB 2: BACKEND
  # =================================================================
  backend:
    name: Backend Pipeline
    needs: changes # wait for job 'changes' to complete first
    if: ${{ needs.changes.outputs.backend == 'true' }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract docker meta data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/baemtli-backend
          tags: type=sha,format=short

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: update Azure container app
        uses: azure/container-apps-deploy-action@v1
        with:
          # AuthN
          registryUrl: ${{ env.REGISTRY }}
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GHCR_AZURE_ACCESS_TOKEN }}

          resourceGroup: dev-rg-baemtli
          containerAppName: baemtli-backend
          imageToDeploy: ${{ env.REGISTRY }}/${{ github.repository_owner }}/baemtli-backend:${{ steps.meta.outputs.version }}

  # =================================================================
  # JOB 3: FRONTEND
  # =================================================================
  frontend:
    name: Frontend Pipeline
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract docker meta data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/baemtli-frontend
          tags: type=sha,format=short

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: update Azure container app
        uses: azure/container-apps-deploy-action@v1
        with:
          # AuthN
          registryUrl: ${{ env.REGISTRY }}
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GHCR_AZURE_ACCESS_TOKEN }}

          resourceGroup: dev-rg-baemtli
          containerAppName: baemtli-frontend
          imageToDeploy: ${{ env.REGISTRY }}/${{ github.repository_owner }}/baemtli-frontend:${{ steps.meta.outputs.version }}